//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Stid { get; set; }
        public int Subid { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
