//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int Pid { get; set; }
        public string Product { get; set; }
        public Nullable<int> PImage { get; set; }
        public Nullable<int> Catid { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ProfitPercentage { get; set; }
    
        public virtual CategoryList CategoryList { get; set; }
        public virtual CategoryList CategoryList1 { get; set; }
        public virtual CategoryList CategoryList2 { get; set; }
    }
}
